### ISSUE TITLE
Wish list, nice to see more samples on 

### ISSUE THREAD

**Issue by boguslawblonski** [Microsoft/SmartHotel360-mobile-desktop-apps#11]
It would be nice to see additional samples:
-Gestures support as swipe on many platforms
-usage of repeater control (not list)  to print items 
-RTL (non latin ) language sample 
-Fault handling on request , many times try to connect,

**Comment by jsuarezruiz** [comment]
Very interesting list. I'm going to add a little more info related to each point in case it helps.

- Related to gestures there are nice libraries like [MR Gestures ](http://www.mrgestures.com/).
- In SmartHotel360 a control similar to Repeater Control is used. There are also some community components. For example [this one](https://github.com/HoussemDellai/Xamarin-Forms-RepeaterView).
- There are recent changes in Xamarin.Forms related to [RTL](https://github.com/xamarin/Xamarin.Forms/pull/1222).
- I recommend this [article ](https://www.davidbritch.com/2017/07/transient-fault-handling-in-xamarinforms.html) by David Britch.
