### ISSUE TITLE
Compile errors in Android project

### ISSUE THREAD

**Issue by angelSwp** [Microsoft/SmartHotel360-mobile-desktop-apps#15]
Hello,
I'm getting the following error message:

Unhandled Exception:

Java.Lang.RuntimeException: Unable to start activity ComponentInfo{com.microsoft.smarthotel/md52696540e2fcaa81fffea6d2d44407794.SplashActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.

**Comment by bradygmsft** [comment]
@angelSwp - could you provide your IDE version number? We're trying to see if maybe there's a tooling update that could resolve this.

**Comment by bradygmsft** [comment]
@angelSwp We tried reproducing this to no avail. Could you you provide us more information about your configuration? Are you still seeing this? We've not heard back in a week so I'm closing this, but please reach out if you're still seeing these issues.
