### ISSUE TITLE
Are there sample endpoints

### ISSUE THREAD

**Issue by Targolo** [Microsoft/SmartHotel360-mobile-desktop-apps#17]
Hi,

To run this application, do you need to build and deploy the backend services or are there sample backend services on Azure that we could use ?

Since that you write in the requirements section that we only need a Bing Maps Key, I thought that all the rest was provided.

Thanks

**Comment by fpelaez** [comment]
hi @Targolo ,
There is a public version of all the back-end services published on Azure so everyone can test the Web Site and the Mobile-desktop apps without having to worry about the back-end. You can find all the public endpoints in the following url http://sh360services-public.eastus2.cloudapp.azure.com/configuration-api/cfg/public-http.

**Comment by bradygmsft** [comment]
@dasanagu - could you add this information to the readme for this repository and then close this issue? thanks!

**Comment by dasanagu** [comment]
The sample endpoints are now in the readme file. https://github.com/Microsoft/SmartHotel360-mobile-desktop-apps/commit/e68356dbef11c793b665fa7a4ca3f298097aa86b

**Comment by bradygmsft** [comment]
@dasanagu excellent! thanks mate!
