### ISSUE TITLE
Fatal exception while deploying on Android 8.0

### ISSUE THREAD

**Issue by orestesgaolin** [Microsoft/SmartHotel360-mobile-desktop-apps#21]
I tried to run the SmartHotel.Clients.Android app on Samsung S8 with Android 8.0. Unfortunately, the app crashes on startup with following exception as the last:

```java.lang.RuntimeException: Unable to start activity ComponentInfo{com.microsoft.smarthotel/md52696540e2fcaa81fffea6d2d44407794.SplashActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.```

Please find the full output log attached: https://gist.github.com/orestesgaolin/81f9ef2246801d744e5f4f7c3968fcec

I use Visual Studio 2017 15.6.2.
I didn't change anything in the provided solution.

**Comment by smeilhac** [comment]
I met the same issue and follow this solution : https://forums.xamarin.com/discussion/comment/183318/#Comment_183318, juste clean all & rebuild all.
