### ISSUE TITLE
ExtendedSplashView

### ISSUE THREAD

**Issue by dyardyGIT** [Microsoft/SmartHotel360-mobile-desktop-apps#26]
What is the value or purpose of ExtendedSplashView? (Android/IOS already show splash screens)

**Comment by mzhukovs** [comment]
Based on the view xaml I am guessing it's to prevent an awkward gap b/w the real splash and the checking of whether user is authenticated (which this view provides an activity indicator for when IsBusy) and the subsequent navigation to either the Home view or Login view. Can any of the project contributors confirm when you have a min? @davidortinau @MihaMarkic @bradygmsft  @davidortinau

**Comment by MihaMarkic** [comment]
Looks like it.
