### ISSUE TITLE
How to add .pfx file to UWP app

### ISSUE THREAD

**Issue by bayernmunich** [Microsoft/SmartHotel360-mobile-desktop-apps#28]
Hi,
I trying out SmartHotel UWP app.Locally in Visual Studio 2017 its building but when i build  that in VSTS using private agent its giving error regarding .pfx.
Which is not available in the source code. How should I create .pfx file?

**Comment by dasanagu** [comment]
Hi @bayernmunich here you can find the instructions for signing the UWP app https://docs.microsoft.com/en-us/windows/uwp/packaging/create-certificate-package-signing
