### ISSUE TITLE
Unnecessary awaiting on event implementations

### ISSUE THREAD

**Issue by MihaMarkic** [Microsoft/SmartHotel360-mobile-desktop-apps#3]
For example:
```
private async void OpenDoorAsync()
        {
            await NavigationService.NavigateToPopupAsync<OpenDoorViewModel>(true);
        }

```
This code doesn't need await nor async. In fact it generates unnecessary code bloat behind the scenes. I'd do it like
```
private void OpenDoorAsync()
        {
            var ignore=NavigationService.NavigateToPopupAsync<OpenDoorViewModel>(true);
        }
```

**Comment by jsuarezruiz** [comment]
First of all, thank you for your contribution. 
I have sent a PR with changes in some asynchronous commands to avoid making unnecessary use of async void.

**Comment by eiximenis** [comment]
PR Merged! Thx to all!!!
