### ISSUE TITLE
UWP_TemporaryKey.pfx

### ISSUE THREAD

**Issue by bayernmunich** [Microsoft/SmartHotel360-mobile-desktop-apps#30]
How can I fix this  problem ?
 C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(3786,5): Error APPX0104: Certificate file 'SmartHotel.Clients.UWP_TemporaryKey.pfx' not found.

**Comment by dasanagu** [comment]
Hi @bayernmunich you can create a key following this guide: https://docs.microsoft.com/en-us/windows/uwp/packaging/create-certificate-package-signing
