### ISSUE TITLE
Compile errors in iOS (Live player)

### ISSUE THREAD

**Issue by mhdmaktabi** [Microsoft/SmartHotel360-mobile-desktop-apps#34]
error: Xamarin.FFImageLoading package not found for versions [2.2.20, ] on netstandard1.4
GreenChart.cs(1,1): error: The type or namespace name 'SkiaSharp' could not be found (are you missing a using directive or an assembly reference?)

GreenChart.cs(1,1): error: The type or namespace name 'SKCanvas' could not be found (are you missing a using directive or an assembly reference?)

Chart\FakeChartService.cs(1,1): error: The type or namespace name 'SkiaSharp' could not be found (are you missing a using directive or an assembly 

\SmartHotel.Clients\MarkupExtensions\TranslateExtension.cs(1,1): error: The type 'IServiceProvider' exists in both 'System.ComponentModel, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.ComponentModel, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

\TemperatureChart.cs(1,1): error: 'TemperatureChart.DrawContent(SKCanvas, int, int)': no suitable method found to override

\MarkupExtensions\TranslateExtension.cs(1,1): error: 'TranslateExtension' does not implement interface member 'IMarkupExtension.ProvideValue(IServiceProvider)'

SmartHotel.Clients\Services\Dialog\DialogService.cs(1,1): error: The type name 'Color' could not be found in the namespace 'System.Drawing'. This type has been forwarded to assembly 'OpenTK-1.0, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065' Consider adding a reference to that assembly.

SmartHotel.Clients.iOS\Renderers\CustomPageRenderer.cs(1,1): error: The name 'NavigationBarAttachedProperty' does not exist in the current context

SmartHotel.Clients.iOS\Renderers\ExtendedEntryRenderer.cs(1,1): error: The name 'ExtendedEntry' does not exist in the current context

\SmartHotel.Clients.iOS\Renderers\CalendarButtonRenderer.cs(1,1): error: The type or namespace name 'CalendarButton' could not be found (are you missing a using directive or an assembly reference?)

\SmartHotel.Clients.iOS\AppDelegate.cs(1,1): error: The type or namespace name 'App' could not be found (are you missing a using directive or an assembly reference?)

\SmartHotel.Clients.iOS\Renderers\CalendarButtonRenderer.cs(1,1): error: The type or namespace name 'CalendarButton' could not be found (are you missing a using directive or an assembly reference?)

\SmartHotel.Clients.iOS\AppDelegate.cs(1,1): error: The type or namespace name 'IBrowserCookiesService' could not be found (are you missing a using directive or an assembly reference?)

**Comment by mhdmaktabi** [comment]
![live1](https://user-images.githubusercontent.com/4623568/42271199-6893a8fc-7f8b-11e8-85f6-09f05b801cbc.png)

**Comment by dasanagu** [comment]
We have fixed this with a latest update.

**Comment by mhdmaktabi** [comment]
![image](https://user-images.githubusercontent.com/4623568/45849575-19e5a280-bd3b-11e8-82be-bea5b3321c78.png)

**Comment by mhdmaktabi** [comment]
@dasanagu it didn't work
