### ISSUE TITLE
Compile errors in iOS Live player

### ISSUE THREAD

**Issue by mhdmaktabi** [Microsoft/SmartHotel360-mobile-desktop-apps#36]
![image](https://user-images.githubusercontent.com/4623568/42244394-86a68f3a-7f1d-11e8-8a3b-4d0bd689d8a0.png)

**Comment by dasanagu** [comment]
Hi! We have fixed this issue with a latest update.

**Comment by mhdmaktabi** [comment]
![image](https://user-images.githubusercontent.com/4623568/45849558-076b6900-bd3b-11e8-9acc-0d5f850507c7.png)

**Comment by mhdmaktabi** [comment]
@dasanagu it didn't work
