### ISSUE TITLE
Xamarin.android version

### ISSUE THREAD

**Issue by halukmy** [Microsoft/SmartHotel360-mobile-desktop-apps#5]
available?

**Comment by eiximenis** [comment]
Hi @halukmy 
The mobile app is a Xamarin Forms application (which runs on Android, iOS, and Windows). There is no "classic Xamarin.Android" app if that is what you are asking for.

**Comment by halukmy** [comment]
thats sucks, i dont like classic form stuff, please update for native

**Comment by MihaMarkic** [comment]
Well, it's a Forms showcase...

**Comment by jsuarezruiz** [comment]
Well, there are three different applications. The main app and the app that makes use of NFC are Xamarin.Forms. There is another Xamarin Native application that makes use of Xamarin.iOS and Native Forms. I do not know if it helps you :).

**Comment by halukmy** [comment]
i was hate before embedded

now i totally support xamarin.forms embedded in Native ^^ thanks
