### ISSUE TITLE
Template?

### ISSUE THREAD

**Issue by mzhukovs** [Microsoft/SmartHotel360-mobile-desktop-apps#9]
This is really great stuff - thanks for putting together, very helpful. Would it be possible to get a TEMPLATE version of this to kick-start a project? I.e. go to create a new project and select this as a template, just enter the solution name and off you go?

**Comment by jsuarezruiz** [comment]
Do you mean a project template?. If so, what do you expect from the template? MasterDetailPage, etc?

**Comment by Nagendrababu61** [comment]
I have little knowledge and intrested to learn Xamarin Forms, 
actually i am  also looking for  template with MasterDetailsPage and LogInPage, Sqlite Connectivity with EntityFramwork more then 3 ViewModels access that CURD operation Methods, With Styles of Login and MasterDetailPage in MVVM. 
I am expecting from This templete...
  * REPORTS TAB & Reports from Micro
  * NFC POPUP
  *  LOGIN  Screen
 

Can you help me plz, If possible.

**Comment by dasanagu** [comment]
Hi @Nagendrababu61 glad you liked this. Unfortunately we are not planning to do templates or customization of this project by now. However you can check the documentation of [Xamarin.Forms templates](https://developer.xamarin.com/guides/xamarin-forms/application-fundamentals/templates) as well you can check some third-party templates. If you would like to learn more about Xamarin.Forms we recommended you this [book](https://developer.xamarin.com/guides/xamarin-forms/creating-mobile-apps-xamarin-forms).
